### ISSUE TITLE
Philips 2018 version

### ISSUE THREAD

**Issue by fastenspy** [skrollme/homebridge-philipstv#3]
Hi, 

I installed the plugin on my Pi. Then I launched the pyton script I received the username and code from the TV. But I have an error, I believe that we must change the API version to 6.1 but how to do it?

Thanks 

```
[12/15/2019, 4:20:56 PM] [TV] getPowerState - Got non JSON answer - not updating state: '<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Not Found</p>
<p>The server has not found anything matching the request URI</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.5">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>
'
```

**Comment by skrollme** [comment]
Because I do not plan to support newer TV-API versions - because I do not own a TV which offers these - try to find a fork of this plugin which support the version you need:
[https://github.com/skrollme/homebridge-philipstv-x/network/members](https://github.com/skrollme/homebridge-philipstv-x/network/members)

**Comment by fastenspy** [comment]
Hello, thanks I will test this ! Thx
